spring.application.name=shop-backend
server.port=8080

#Datasource Config
spring.datasource.url=jdbc:postgresql://localhost:5432/shopdb
spring.datasource.username=shop
spring.datasource.password=shop
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

# Liquibase Config
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.liquibase.enabled=true
spring.liquibase.contexts=dev

#Spring Doc
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

# Keycloak Config
keycloak.issuer-uri=http://localhost:8081/realms/shop
keycloak.client-id=shop-api

#logging
logging.level.org.hibernate.SQL= warn
logging.level.liquibase= debug

#Endpoint Health
management.endpoints.web.exposure.include=health
management.endpoints.health.show-details=never


